#! /bin/sh

if [ $# -lt 1 ]; then
        exit 1
fi

GRAY=`identify -verbose $1 | grep mean: | awk -F\: '{print $2}' | awk '{print $1}' | awk -F\. '{print $1}'`

GRAY=`echo $GRAY | awk '{print $1}'`

area_is_blank() {
        if [ $GRAY -eq 255 ]; then
                exit 1
        else
                exit 0
        fi
}

area_is_blank
