#! /bin/sh
# $1 is mouse position (Point)

# This file is copy from dbound, Symbol is nothing :-)

AREA=sc.png
STEP=4
EXP_VAL=3

camera() {
        ox=`echo $1 | awk -F, '{print $1}'`
        oy=`echo $1 | awk -F, '{print $2}'`

        x1=$[$ox-$EXP_VAL];
        y1=$[$oy-$EXP_VAL];

        x2=$[$ox+$EXP_VAL];
        y2=$[$oy+$EXP_VAL];

        echo $x1,$y1 $x2,$y2
}

upper_camera() {
        # $1 is Camera

        
        x1=`echo $1 | awk '{print $1}' | awk -F, '{print $1}'`
        y1=`echo $1 | awk '{print $1}' | awk -F, '{print $2}'`


        x2=`echo $2 | awk '{print $1}' | awk -F, '{print $1}'`
        y2=`echo $2 | awk '{print $1}' | awk -F, '{print $2}'`

        x1=$[$x1+$STEP]
        x2=$[$x2+$STEP]

        echo "$x1,$y1 $x2,$y2"
}

dbound() {
        local new_camera=`camera $1`
        ./capture_area $new_camera
        ./area_is_blank $AREA
        while [ $? -eq 0 ]; do
                new_camera=`upper_camera $new_camera`
                ./capture_area $new_camera
                ./area_is_blank $AREA
        done
        echo $new_camera # | awk '{print $1}' | awk -F, '{print $1}'
}


if [ $# -lt 1 ]; then
        exit 1
fi

dbound $1
